apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: frontend-mongo-pacman-zyzp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: frontend-mongo-pacman-zyzp
    app.kubernetes.io/part-of: my-app
  name: frontend-mongo-pacman-zyzp
  namespace: user1-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: frontend-mongo-pacman-zyzp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: frontend-mongo-pacman-zyzp
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
        image: quay.io/jduimovich0/user-workload@sha256:e63c701e03c0b0ef71046006f9db513112208cd16bf3433528eb17249fb9a581
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
