apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mongo-mongo-pacman-o7tz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mongo-mongo-pacman-o7tz
    app.kubernetes.io/part-of: my-app
  name: mongo-mongo-pacman-o7tz
  namespace: user1-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: mongo-mongo-pacman-o7tz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: mongo-mongo-pacman-o7tz
    spec:
      containers:
      - image: quay.io/jduimovich0/user-workload@sha256:2d4962a5cf367b6fff9ad4bbee781c5131a9322f8bc0fd83d4db9a10312b0051
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 512Mi
status: {}
